FROM osrf/ros:noetic-desktop-full

# https://github.com/ethz-asl/kalibr/wiki/installation
RUN apt-get update && DEBIAN_FRONTEND=noninteractive \
	apt-get install -y \
	git wget autoconf automake nano \
	python3-dev python3-pip python3-scipy python3-matplotlib \
	ipython3 python3-wxgtk4.0 python3-tk python3-igraph python3-pyx \
	libeigen3-dev libboost-all-dev libsuitesparse-dev \
	doxygen \
	libopencv-dev \
	libpoco-dev libtbb-dev libblas-dev liblapack-dev libv4l-dev \
	libyaml-cpp-dev \
	python3-catkin-tools python3-osrf-pycommon \
	&& rm -rf /var/lib/apt/lists/*

# Set environment variable for manual focal length init
ENV KALIBR_MANUAL_FOCAL_LENGTH_INIT=1

# Setup bashrc for ROS and kalibr
RUN echo 'source /opt/ros/noetic/setup.bash' >> ~/.bashrc && \
	echo 'source /workspaces/kalibr/devel/setup.bash 2>/dev/null' >> ~/.bashrc && \
	echo 'export KALIBR_MANUAL_FOCAL_LENGTH_INIT=1' >> ~/.bashrc && \
	echo 'export PATH=$PATH:/workspaces/kalibr/devel/lib/allan_variance_ros' >> ~/.bashrc

# Note: For devcontainer usage, the workspace is mounted at /workspaces/kalibr
# This Dockerfile only installs dependencies, it does NOT copy or build the source
